trigger:
- main
- master

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Run Maven to build and package the application
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Step 2: Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    testRunTitle: 'Maven Test Results'
  displayName: 'Publish Maven Test Results'

# Step 3: Debug application and environment
- script: |
    echo "Debugging pipeline environment..."
    echo "Web application accessibility test:"
    curl -I https://rafazuredevops-example-ckfaczfmevaebhdh.canadacentral-01.azurewebsites.net/webapp/
  displayName: 'Debug Application and Environment'

# Step 4: List contents of the artifact staging directory for debugging
- script: |
    echo "Listing contents of the artifact staging directory..."
    ls -la $(Build.ArtifactStagingDirectory) || echo "No files found in artifact staging directory."
  displayName: 'Debug Artifact Staging Directory'

# Step 5: Copy .war files to the artifact staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy WAR files to artifact staging directory'

# Step 6: Debug and list the temporary task outputs directory
- script: |
    echo "Checking the temporary task outputs directory..."
    ls -la /home/vsts/work/_temp/task_outputs || echo "Directory does not exist or is empty."
  displayName: 'Debug Task Outputs Directory'

# Step 7: Publish the artifact to Azure DevOps
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'warfile'
  displayName: 'Publish WAR file artifact'

# Step 8: Build and push Docker image with versioning
- task: Docker@2
  inputs:
    containerRegistry: 'rafdocker1' # Replace with your container registry service connection
    repository: 'sonako2000/azuredevops-1' # Replace with your Docker repository
    command: 'buildAndPush'
    Dockerfile: 'AzureDockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(Build.BuildId)
      latest
  displayName: 'Build and Push Docker Image with Tags'
